# Generated by Django 5.2.4 on 2025-08-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='avg_price',
        ),
        migrations.AddField(
            model_name='stockprice',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='open',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='volume',
            field=models.BigIntegerField(null=True),
        ),
    ]
