# Generated by Django 5.2.4 on 2025-07-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
